const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})

const interviewReportSchema = z.object({
    matchScore: z.number().min(1).max(100).describe("A score between 1 and 100 indicating how well the candidate's performance matches the job description"),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question that can be asked in an interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Technical questions that can be asked in the interview along with their intention and how to answer them"),
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral question that can be asked in an interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Behavioral questions that can be asked in the interview along with their intention and how to answer them"),
    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill which the candidate is lacking"),
        severity: z.enum([ "low", "medium", "high" ]).describe("The severity of the skill gap, can be low, medium or high")
    })).describe("List of skill gaps in the candidate's profile along with their severity"),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day number in the preparation plan, starting from 1"),
        focus: z.string().describe("The focus of the day, what to study, what to practice etc."),
        tasks: z.array(z.string().describe("List of tasks to be done on this day to follow the preparation plan, e.g. practice coding questions, read articles, watch videos etc."))
    }).describe("A day-wise preparation plan for the candidate to follow in order to prepare for the interview effectively")),
    title: z.string().describe("The title of the job for which the interview report is generated.")
});

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
    const prompt = `Generate an interview report for the candidate with the following details:
                    Resume: ${resume}
                    Self Description: ${selfDescription}
                    Job Description: ${jobDescription}
                    `;

    const rawSchema = z.toJSONSchema(interviewReportSchema);
    delete rawSchema.$schema;

    const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-lite",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseJsonSchema: rawSchema,
        }
    });

    return JSON.parse(response.text);
}


async function generatePDFFromHTML(htmlContent) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0', margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" } });

    const pdfBuffer = await page.pdf({ format: "A4" });

    await browser.close();

    return pdfBuffer;
}

async function generateResumePDF({ resume, selfDescription, jobDescription }) {
    const resumePDFSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using a library like puppeteer")
    })

    const prompt = `Generate a resume for candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single key "html" which contains the HTML content of the resume which can be converted to PDF using a library like puppeteer
                        the resume should be tailor made for the job description provided and should highlight the skills and experiences of the candidate which are relevant to the job description. The resume should be in a professional format and should be visually appealing. The resume should be in a single page format and should not exceed one page in length.
                        The content of the resume should not sound like it is generated by AI and should be unique and original.
                        You can highlight the content using some colors and fonts but make sure that the resume is not too flashy and is professional in appearance.
                        the content should be ATS friendly, i.e. it should be easily readable by Applicant Tracking Systems and should not contain any images or graphics which can hinder the readability of the resume by ATS. 
                        The resume should not be so lengthy that it exceeds one page in length and should be concise and to the point. The resume should be in a format which can be easily converted to PDF using a library like puppeteer.
                    `;

    const rawSchema = z.toJSONSchema(resumePDFSchema);
    delete rawSchema.$schema;

    const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-lite",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseJsonSchema: rawSchema,
        }
    });

    const jsonContent = JSON.parse(response.text); 

    const pdfBuffer = await generatePDFFromHTML(jsonContent.html);

    return pdfBuffer;
}

module.exports = { generateInterviewReport, generateResumePDF };

